### ISSUE TITLE
Paypal encrypted website payments error

### ISSUE THREAD

**Issue by jmiridis** [jmiridis/atcsf1#1]
I am using Encrypted Website Payments and I am getting the following error after replacing expired certificates with new ones:

![image](https://user-images.githubusercontent.com/1295390/38060579-f57faf9a-32b0-11e8-861d-6a219e217535.png)
 
There have been no changes to the application code, so I can exclude the possibility that the error has been introduced in the code.

These are my certificates registered with Paypal:

![image](https://user-images.githubusercontent.com/1295390/38063339-36c751ee-32be-11e8-8609-3605c84cf08d.png)

They have been generated like this and then uploaded the public key:
```
openssl genrsa -out my-prvkey.pem 1024
openssl req -new -key my-prvkey.pem -x509 -days 365 -out my-pubcert.pem
```

The following link takes you to a sample reservation where the user can click on the encrypted payment button:

http://americantransferscancun.com/access/yykBIKsaGtJy1MCScCJlQUe9v2PuLzS9jiHXu0kRYtamS-fzjz5lwLyFw67XdZzTRbbJMNe3FjDTU7isDTS0Qg

![image](https://user-images.githubusercontent.com/1295390/38060633-3005049e-32b1-11e8-9d01-1c96fabe49e4.png)

The generated form and input fields look like this:

```html
<form method="post" action="https://www.paypal.com/cgi-bin/webscr">
<input name="cmd" value="_s-xclick" type="hidden">
<input name="encrypted" value="-----BEGIN PKCS7-----MIIJFQYJKoZIhvcNAQcDoIIJBjCCCQICAQAxggE8MIIBOAIBADCBoDCBkjELMAkGA1UEBhMCTVgxDjAMBgNVBAgMBVEuUk9PMQ8wDQYDVQQHDAZDYW5jdW4xIDAeBgNVBAoMF0FtZXJpY2FuVHJhbnNmZXJzQ2FuY3VuMQwwCgYDVQQDDANBVEMxMjAwBgkqhkiG9w0BCQEWI2NvbnRhY3RAYW1lcmljYW50cmFuc2ZlcnNjYW5jdW4uY29tAgkAvuEz/G5mVGYwDQYJKoZIhvcNAQEBBQAEgYBjvH5S1aqCeS0K9xDd11yAapue8OMydzMeDMjXvZIipTV9CxfKIx2od7vpnqf09SKmDkV/6WrXi1XpciaY5SfMrMUsoiMet7PCFoxoiSmrsrO2nuDWrV6XMsevM2H/sHSk6lgM2MARjvE1lGb/2CLl6L20poI3M8kURB2jEOHDkjCCB7sGCSqGSIb3DQEHATAaBggqhkiG9w0DAjAOAgIAoAQIPvw8PNAxp/+AggeQV+s3cchxBzVGv432PZnr0IGjLzxQoJbaydTDG6xjUMvXgnZ997XJB46OJdSCFdK8oqnfnT9NzDlIlIKAYHI6K2hCwb8mNdhEOns78RuYthG8OpfAZWpv+shmDN0WWrJnon7VBQZHPiMvlk3axdgFERIK8DOa3s+zcGC/u1fwjrYyVW7r1Kw6AAjke4lrQp/bAcZdwLreyv+NFcwZQObj5C+baSpaEq8JLNAbHqwo5A60AXWmiR6aY5z9ft6e8YTiFyLZiCYBsuVDQ1oI3OoixbW1jzAELYK9u4/oY40xgd4Qxn6PTRX7JCMJ/x0TEG1YlI+uP6TpBNe2iQ95ZuyhgigXmemR6/NUnfdJ+lMpxDQiIsuOePo8HymBprlgJ83DecFGYMHxXgAAVMY6Ls7H4sDNklb27tsZ0lP/uQA4KNHpCouJPWq58nxjZ6DUJguiCfPYqvRcaBt1zHwIJBdam4PrNTWBJDGcVALoz8fID55eKz5G+FD33g/+bUgnrW8BB5Uybb7LCnHGVAwoFQUhY0pcX0M5TrlbOt/0gk1v0PZj1rteMNYBgN0ZffHqRF2B15aVgbJSUyu6LP3VFoV+UPQUSvQA1tu6x2BcdyFwbYjqfrTcA+Fvw6iQl/ada383eDxShGa/DHUdKxvCg67R1ufkflHJCHrQdXASmcgptO77mTfiSf914NJmbnyUbclIYkq/XqkE2BzmLMg9Fr0v2BN3b9faIsA+l/gQKe2Lj9iBQ6cTV4uKQcI7xiH8e/VYuW+I9as/ez7S8NHZ4Qd8u/CnGFks5S04namxRjil2GXWZ8pEBDvnEJ6FEL7vn0KgX3Xzt4ixCnmlK1lmoefbevToXCPFOS18mHuPg+MC3dXpN01DJH3eMLjzRITrmqXOgRMFGQbRgT1DsQaXc2ejjh7fjUDdbKatlEI4ItD1zfqK0uQm5NV6Qk6K7p3IuAbcndTR83Pu70M6AbgwoNjer51zVLnyIA9hrSkyMM6t5g4KJi3DZyTB4L6yIESVpjQCGUHPCWI0mmcus/Z9n6P14HxixGX1T2WOMwZmKBaFXbTNQOPrE9uo1RoI1jjN8g7D1tQ5NhkU4JSHQtmgHtP30mu+CQwMMJdXlCorlT7MburbtS4YlEiNm6i43ZxMJO8ByHwtOO1D9AhxP8/xhdiY2SXocr+lJIPdAUpyniIxYp6qOrHFBHsLDAQCU9cVb7ke74SOyT/k3P1+ph46EX4f8oUF3iTZhvtWU5E0xkqz11Q5OjObr/Rf+G779tf0uZ0dt9dpwOUTUaTyI31iIX+RlZJ8aJeM44y5y0zQdkmx80+zQ21oZibtv+w7hTCosOeCTH7laTaAAKWMhu7pTzjKVbxvzkpLLNtL+eOWcFcXG0vV4m/XmclXyWUFrUzZ4dAzOT+5J/7tltQOIb/5vUOGkQX+oKneS0em5RJ+wLI8ZpEmccOn7UhMYV1cM0ytrkFScv8Zz8hjj/xXVkKbkj3qYRTC3fbtxNeHn+ZNQgeObLS0A7l8oAqXHcq50vyhBBRr5M9/hUjPvAKBZhIPTN8VVWr6JSsVYeT+KmtseU0YiHoFlV53As1QCf3p4rh3jhnXSiZ27FpJcwKrYMkclGiOGxYXrdFns2yy954edmV9W+CwbS33gffSycOXnThwdGsL7CdCG9bqKVcjuXR9mjOX5cduecWv/+0rjD/GzDxGgBoUn/eDuhr6WN8hRQE6/LDIRTkcLNfOSjBWVKNBSMn9WRg7VGx19qIWTythJVVhKSNikTPYFRU0VPVMVpFhViuU3rb6bXqtVfzvbqZZZvLsPNb7UfoPaIJ2IHCJp1KJIZOaTwet9PWW0rMCfeuuqJcsR2ojiHP7Mb+cN5WriHLD5ueCyPsJVoa+u1v+RQsnKzdpZaLNeVGABlEKSnESXZVdXN35EkEKSiggUKZkIwvC5tZQWez3Bgo4xCbQxWaJC17ugv3PFeIMXseIjNbzMbbhfN79FDIOmbfMP3O8iuWbtqeLOFuZ5l+gumRywDrxXK5MCZO7OlXfxqweeztSrpjrsbSNlWFCjmiqtA0RLJTH5FBIzSMUOq/Dop/WkJPd6sUSwFHgAY4jbf03cHyQhzY1mQjdiIcb4PAen9+VwhtJ+ArP/Mnbe1TBZQH10OjTFSq4t5S6gTgTSAqd2rsud0qq1QHYdOvqcbpsxRJu+Yw/RUCGqlS6xKlMPsb91P1ODUvzXOQRyXDiwQ6gk5wifLf+JrRs0OyDb7uuBCdhC5XAQ0Q2URBTEh06ELK6FJoD3veqGVWSLT9oMTIrwKzG0GyO8yquB4igZWzAxThur0hlkM2MARoEqrF+0hGLVkGsetoPARPszpF+mGBqmPJr1SX2aK7Jq7D8RG8GnhETmebSbQ9+OsPrBuZRo5H8SwaV4yEcV8mJWgkiaSVT9gUV84nbheXA0GCCcdp9xf7ymcmhRStXNY+T0ZR59RwywerU0NvRYAOmBRSd1VJHpOb4uE6gCJtEMEDzXgiAzW1Rsi7jkis+YOUd5t5AHT186mQVkBheOvpYhb5pMRn0UGQE50xvvNqF5QoMIs/yg0U6QkXG7g==-----END PKCS7-----" type="hidden">
<input src="https://www.paypal.com/en_US/i/btn/btn_paynowCC_LG.gif" alt="PayPal - The safer, easier way to pay online!" type="image">
</form>
```

The PHP application which is using the certs and generating the encrypted button, has a parameter file where the certificate id and the path to the certificates are defined. I have uploaded the certificates and updated the parameter file and we can assume that there is no error there as the encryption process throws no error.

I am providing the following code samples only for a better understanding of the application, not because I think that there is a problem. 

This is an excerpt of the parameters file https://github.com/jmiridis/atcsf1/blob/master/apps/frontend/config/app.yml:

```yaml
prod:
#===============================================================================
# esPaypalPlugin
#===============================================================================
  es_paypal_plugin:
# activate/deactivate test mode (sandbox)
    test_mode: false
# activate/deactivate debug mode (log/paypal.log)
    debug_mode: true
# The email address of the Paypal seller account
    business: payments@americantransferscancun.com
# Button ecryption requires 3 encryption keys and the certificate id assigned by Paypal
# Login to your merchant account and go to the following link to find more information
# https://www.paypal.com/us/cgi-bin/webscr?cmd=_profile-website-cert
# ewp =  encrypted website payments
    certificate:
      cert_id: 26G8ZLXR6NFQL
      ewp_prvkey_fname: %SF_DATA_DIR%/certificates/prvkey_26G8ZLXR6NFQL.pem
      ewp_cert_fname:   %SF_DATA_DIR%/certificates/cert_26G8ZLXR6NFQL.pem
      pp_cert_fname:    %SF_DATA_DIR%/certificates/paypal_26G8ZLXR6NFQL.pem
```

This is the relevant snippet of the button encryption class:
https://github.com/jmiridis/atcsf1/blob/master/plugins/esPaypalPlugin/lib/esPaypalButton.class.php

```php
    $pp_encryptor  = new esPaypalEncryptor();
    $pp_encryptor->setCertificate($certificate['ewp_cert_fname'], $certificate['ewp_prvkey_fname']);
    $pp_encryptor->setCertificateID($certificate['cert_id']);
    $pp_encryptor->setPayPalCertificate($certificate['pp_cert_fname']);
    //--------------------------------------------------------------------------
    // define button fields
    //--------------------------------------------------------------------------
    $parameters = array(
      'cmd'       => '_s-xclick',
      'encrypted' => $pp_encryptor->encryptData($this->fields)
    );
```
The PEM files can be found here:
These are my certificates:
https://github.com/jmiridis/atcsf1/tree/master/data/certificates
